#!/bin/bash
mkdir -p .gen
rm -rf .gen/src
cp -r src .gen/
chmod -R a-x+X .gen/src/python
for file in $(find .gen -name ".__init__.py")
do
    echo mv $file `echo $file | sed s/\\\\.__init__/__init__/` | sh
done
tools/.virtualenv/bin/python3 tools/modify_scripts.py
