#!/bin/bash
echo 'running selected tests'
rm -rf gen/src
cp -r src gen
gen/tools/virtualenv/bin/python3 src/tools/modify_scripts.py
gen/tools/virtualenv/bin/nosetests --with-progressive gen/src/python -a 's'
